---
- hosts: repo
  strategy: free
  become: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname repo.test.example.com
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding control address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.60 control.test.example.com control
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.59 repo.test.example.com repo
      create: yes
  - name: Adding node1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.61 node1.test.example.com node1
      create: yes
  - name: Adding node2 IP address to hosts file.
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.62 node2.test.example.com node2
      create: yes
  - name: Adding node3 IP address to hosts file.
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.63 node3.test.example.com node3
      create: yes
  - name: Enabling services
    shell: for i in httpd firewalld chronyd ; do systemctl enable $i;done
  - name: Starting services
    shell: for i in httpd firewalld chronyd ; do systemctl start $i;done
    ignore_errors: true
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Setting SELinux To Permissive
    shell: setenforce 0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Fixing SELinux Contexts
    shell: restorecon -Rv /var/www/html
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into `hostname`
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # You are logged in as `whoami`
         #
         "
...